### ISSUE TITLE
Add cleared and confirmed timestamps to batches

### ISSUE THREAD

**Issue by jamaljsr** [lightninglabs/pool#170]
It would be useful to be able to obtain the timestamp that past batches were cleared on the server. This information is currently not possible to obtain. You can get a rough idea by querying a block explorer for the batch txid, seeing what block the tx is in and using the block's timestamp. This value will always be inaccurate since the batch tx is not guaranteed to be in the next block, it can be many blocks later if a low fee rate is used.

It would also useful to know the timestamp that a batch is confirmed on-chain in order to not have to query a block explorer as mentioned above.

**Comment by halseth** [comment]
Fixed by https://github.com/lightninglabs/pool/pull/193 ?

**Comment by guggero** [comment]
No, the confirmed timestamp is still missing. That'll require more data to be added to the DB. Will probably be a bit easier once we've switched to using TLV in most places.
